import sqlite3

DB_FILE = "CSCI375team3.db"

def insert():
        conn = sqlite3.connect(DB_FILE)
        cursor = conn.cursor()
        
        cursor.executemany("""
                INSERT INTO Courses (courseID, courseName, description, recommendHours, courseDifficulty, sections, reccommendedYear, term
                VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            """, [
                    ('CSCI 112','Applications Programming','An introduction to the use and customization of application packages. Includes macro programming as well as visual programming.', 0, 0,'All Sections', 1,'Both'),
                    ('CSCI 115','Introduction to Web Page Development ','An introduction to Web page construction for students not majoring in Computer Science. The course focuses on client-side techniques: Hypertext Markup Language (HTML, XHTML), Cascading Style Sheets (CSS), and an introduction to JavaScript. Computer Science students may take this course for credit towards their major in Computer Science. ', 0, 0,'All Sections',1,'Both'),
                    ('CSCI 159','Computer Sciece I','A first year course in computer science. Topics include structured programming, top-down program design, procedures, recursion, and an introduction to dynamic data structures.', 0, 0,'All Sections', 1,'Both'),
                    ('CSCI 160','Computer Science I for Engineering','A first year course in computer science. Topics include structured programming, top-down program design, procedures, recursion, and an introduction to dynamic data structures.', 0, 0,'All Sections', 1,'Both'),
                    ('CSCI 161','Computer Science II','Topics include an introduction to objects, classes, object-oriented programming techniques (encapsulation, inheritance, and polymorphism), dynamic data structures (dynamic arrays, linked lists and trees), and abstract data types (stacks, queues and dictionaries).', 0, 0,'All Sections', 1,'Both'),
                    ('CSCI 162','Topics in Computer Science','An introduction to applied and theoretical topics, designed to develop an understanding of key concepts in computer science. Topics include digital logic, programming language paradigms including logic and functional programming, computer organization and architecture, system software, software engineering principles, and theory of computation.', 0, 0,'All Sections', 1,'Both'),
                    ('CSCI 251','Systems and Networks','An introduction to operating systems and computer networks. Topics include network architectures, communications protocols, client / server architecture and file systems. The lab component includes hardware and software installations, upgrades and backups.', 0, 0,'All Sections', 2,'Both'),
                    ('CSCI 260','Data Structures','An examination of various methods of representing and manipulating data, including internal representation of data, stacks, queues, linked lists, trees and graphs. Analysis of algorithms will also be discussed extensively. ', 0, 0,'All Sections', 2,'Both'),
                    ('CSCI 261',' Computer Architecture & Assembly Language ','An introduction to computer organization, and machine and assembly languages. Topics include data representation, the instruction set and addressing modes of a chosen processor, procedures and parameter passing, and the use of operating system services.', 0, 0,'All Sections', 2,'Both'),
                    ('CSCI 265','Software Engineering','An exploration of the methods and tools for developing high quality software. The course includes topics in program design, program style, algorithm selection, interface design, debugging and testing, system utilities, version control, regular expressions and an introduction to scripting languages.', 0, 0,'All Sections', 2,'Both'),
                    ('CSCI 301','Introduction to the Practice of Cyber-Security ','An introduction to key cyber-security concepts as applied to information systems in a business environment. Topics include assessing risk in cyber-security, attack vectors, tenets of cyber-security, the human element, operation security, application security, mobile and IoT security, and incident response plans.', 0, 0,'All Sections',3,'Both'),
                    ('CSCI 307','Preparation for Co-operative Education Employment','Preparation for first co-operative education experience through practical training in areas such as resume writing and interview skills.', 0, 0,'All Sections',3,'Both'),
                    ('CSCI 308','Co-operative Work Placement I','Individual students are carefully matched to employers who supervise them and evaluate their performance during paid work experience. University personnel conduct monitoring. Students will write a work placement report.', 0, 0,'All Sections',3,'Both'),
                    ('CSCI 309','Co-operative Work Placement II ','The second work placement, as described for CSCI 308', 0, 0,'All Sections',3,'Both'),
                    ('CSCI 310',' Introduction to Human-Computer Interaction ','An introduction to understanding human behaviour as it applies to interface design, implementation, and evaluation. Topics include: design issues and goals, the limits of the human cognitive system, user-centered design, prototyping, establishing requirements, evaluation techniques, and design implications of emerging technologies. ', 0, 0,'All Sections',3,'Both'),
                    ('CSCI 311',' Web Programming','Exploration of languages, tools and techniques to write software for use within the World Wide Web (WWW). The course includes the WWW client/server model and related protocols, web server properties, web markup languages, client/server scripting tools, server side programming, and database access tools.', 0, 0,'All Sections',3,'Both'),
                    ('CSCI 320','Foundations of Computer Science ','A survey of formal models and results that form the theoretical foundation of computer science. Typical topics include finite automata, Turing machines, simple undecidable problems, context-free languages, grammars and elementary computational complexity.', 0, 0,'All Sections',3,'Both'),
                    ('CSCI 330','Programming Languages','The fundamental concepts of imperative and applicative programming languages. Topics include the description of data types, variable assignment and sharing, sequencing, iteration and recursion, parameter passing mechanisms, and type checking.', 0, 0,'All Sections',3,'Both'),
                    ('CSCI 331','Object-Oriented Software Development ','Topics include aspects of object-oriented analysis, design and development; definition and comparison of object-oriented metrics; verification methods for OO-software; maintenance and reuse issues.', 0, 0,'All Sections',3,'Both'),
                    ('CSCI 355','Digital Logic and Computer Organization','The fundamentals of logic design, computer organization, and the structure of major hardware components of computers. Topics include the application of Boolean algebra to switching circuits; the use of MSI, LSI and field programmable devices in digital design; combinatorial and sequential circuits, flip flops, counters, memory organization, CAD tools.', 0, 0,'All Sections',3,'Both'),
                    ('CSCI 360','Intro to Operating Systems','An introduction to the major concepts of operating systems and study of the interrelationships between the operating system and the architecture of computer systems. Topics include operating system structures, concurrent programming techniques, cpu scheduling, deadlocks, memory management, file systems and protection. ', 0, 0,'All Sections',3,'Both'),
                    ('CSCI 370','Database Systems ','An introduction to the use and operating principles of database management systems. Topics include data entities and relationships, data modelling using Entity-Relationship Diagrams, hierarchical, network and relational models of databases, query language, physical representation of data in secondary storage, relational algebra and calculus as applied to the design of databases, security and integrity in the context of concurrent use, and basic ethical issues associated with database design and use.', 0, 0,'All Sections',3,'Both'),
                    ('CSCI 375',' Intro to Systems Analysis ','The methods and methodologies used in analyzing and designing various types of systems. Topics include project definition, CASE tools, data gathering, structured analysis and design, human-machine interface, database design, system controls, hardware selection and system testing, implementation and operation. Students are assigned to a project team involved in a system study as part of the course.', 0, 0,'All Sections',3,'Both'),
                    ('CSCI 400','Computers and Society','An introduction to the social, philosophical and ethical issues of technology with an emphasis on computing technology. Topics covered include privacy, social control, information, the changing nature of work and appropriate technology. ', 0, 0,'All Sections',4,'Both'),
                    ('CSCI 405','Computer Graphics ','The fundamental algorithms and data structures used in generative computer graphics. Topics include structure of interactive graphics programs, raster algorithms, colour, two- and three-dimensional geometric transformations, animation, parallel and perspective projection, hidden line and hidden surface algorithms, cubic curves and surfaces, and shading models. Optional topics include fractals/L-systems, and GPU hardware programming.', 0, 0,'All Sections',4,'Both'),
                    ('CSCI 408','Co-operative Work Placement III ','The third work placement, as described for CSCI 308.', 0, 0,'All Sections',4,'Both'),
                    ('CSCI 409','Co-operative Work Placement IV ','A survey of advanced topics in algorithm design and analysis. Typical topics include complexity analysis, strategies for intractable problems, approximation algorithms, random algorithms, advanced data structures for sorting and searching, graph and network algorithms, amortized analysis. ', 0, 0,'All Sections',4,'Both'),
                    ('CSCI 422','Advanced Algorithms ','This course examines selected emerging and advanced topics in Algorithms and Complexity Theory. Topics may include: advanced techniques for algorithm analysis; complexity classes; algorithmic techniques in graph theory, combinatorics, and optimization; approximation algorithms; distributed and parallel algorithms; probabilistic algorithms; online algorithms; quantum algorithms. May be taken more than once in different topics with permission of Department Chair. CSCI 429 was formerly called CSCI 485C; credit will not be granted for both courses.', 0, 0,'All Sections',4,'Both'),
                    ('CSCI 429','Advanced Topics in Algorithms and Complexity ','desc', 0, 0,'All Sections',4,'Both'),
                    ('CSCI 439','Advanced Topics in Programming ','This course examines selected emerging and advanced topics in programming. Topics may include: a detailed analysis of language design, semantics, verification, resource utilization, language support for concurrency, meta-programming, and compilers. May be taken more than once in different topics with permission of Department Chair.', 0, 0,'All Sections',4,'Both'),
                    ('CSCI 460','Networks and Communications ','An introduction to computer networks and communications. Topics include local and wide area networks, network architectures, security, communications protocols, routing, and an introduction to distributed computing.', 0, 0,'All Sections',4,'Both'),
                    ('CSCI 461','Embedded and Real-Time Software Systems ','The theory and practice of developing embedded systems with time and resource constraints. Students design, develop and deploy embedded systems on hardware ranging from bare-metal micro-controllers to systems with a real-time OS to Embedded Linux systems. Time-oriented topics include bare-metal programming, cooperative multitasking and preemptive multitasking.', 0, 0,'All Sections',4,'Both'),
                    ('CSCI 465','Advanced Topics in Software Engineering ','This course examines selected emerging and advanced topics in software engineering. Topics may include: software verification and validation techniques, techniques to model and analyze software processes, software design for various architectures (service-oriented, component-oriented, message-oriented), automation of software delivery pipelines, case studies of large scale software successes and failures. May be taken more than once in different topics with permission of Department Chair.', 0, 0,'All Sections',4,'Both'),
                    ('CSCI 469','Advanced Topics in Systems','This course covers selected emerging and advanced topics in Systems. Topics may include: system programming, distributed systems, peer-to-peer systems, clustered systems, distributed file systems, replicated systems, content distribution systems, fault-tolerant systems, multimedia systems, real-time systems, virtualized systems etc. May be taken more than once in different topics with permission of Department Chair.', 0, 0,'All Sections',4,'Both'),
                    ('CSCI 478','Advanced Topics in Data Science ','This course examines selected emerging and advanced topics in Data Science. Topics may include: big data, data visualization techniques, data mining, statistical modeling and prediction, emerging data analysis techniques. May be taken more than once in different topics with permission of Department Chair.', 0, 0,'All Sections',4,'Both'),
                    ('CSCI 479','Advanced Topics in Artificial Intelligence ','This course examines selected emerging and advanced topics in Artificial Intelligence. Topics may include: searching strategies, constraint satisfaction, game playing, knowledge representation and reasoning, machine learning, applications to robotics. May be taken more than once in different topics with permission of Department Chair. ', 0, 0,'All Sections',4,'Both'),
                    ('CSCI 485','Advanced General Topics in Computer Science ','This course covers selected emerging and advanced topics in Computer Science. Topics may include: programming, systems, software engineering, human computer interaction, algorithms, artificial intelligence, data science, robotics. May be taken more than once in different topics with permission of Department Chair. ', 0, 0,'All Sections',4,'Both'),
                    ('CSCI 485C','Topics in Systems: Advanced Algorithms ','Offered as CSCI 485A, 485B, 485C, 485D. Topics depend primarily on the interests of the instructor. Entry is restricted to third and fourth year students who meet the prerequisite specified for the topic to be offered. May be taken more than once in different topics with permission of department Chair. ', 0, 0,'All Sections',4,'Both'),
                    ('CSCI 485F','Topics in Systems: Array Programming ','Topics depend primarily on the interests of the instructor. Entry is restricted to third and fourth year students who meet the prerequisite specified for the topic to be offered. May be taken more than once in different topics with permission of department Chair.', 0, 0,'All Sections',4,'Both'),
                    ('CSCI 490','Independent Project ','A one-semester independent research and development project under faculty supervision. Includes required research and development as per an approved project proposal, and preparation of a written report detailing the results.', 0, 0,'All Sections',4,'Both'),
                    ('CSCI 491',' Senior Research Project ','An opportunity for student experience in research and development under the supervision of a faculty member in Computing Science. Project duration is two academic terms during which time a student must develop an approved project proposal, carry out the required research and development, prepare a written report detailing results, and satisfy any additional requirements as specified in the approved project proposal.', 0, 0,'All Sections',4,'Both')
                ])
        conn.commit()
        conn.close()

if __name__ == "__main__":
        insert()
        